### ISSUE TITLE
米游社签到报错

### ISSUE THREAD

**Issue by Cute-angel** [y1ndan/genshinhelper2#14]
2022-01-09 09:33:40 ERROR TRACEBACK
Traceback (most recent call last):
  File "/app/./genshincheckinhelper/main.py", line 245, in run_task
    raw_result = func(cookie)
  File "/app/./genshincheckinhelper/main.py", line 90, in task2
    r = t.sign()
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/core.py", line 114, in sign
    user_data = self.user_data
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/core.py", line 103, in user_data
    current_reward = self.current_reward
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/core.py", line 84, in current_reward
    return [
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/core.py", line 85, in <listcomp>
    self.get_current_reward(i['total_sign_day'], i['is_sign'])
KeyError: 'total_sign_day'
2022-01-09 09:33:40 INFO RESULT:
🏆 原神签到福利
☁️ ✔ 0 · ✖ 1
🌈 No.1:
    'total_sign_day'

2022-01-09 09:33:40 INFO Preparing to send notification ...
2022-01-09 09:33:43 INFO End of process run

**Comment by Cute-angel** [comment]
解决了，之前的cookie没有account_id和cookie_token重新登陆就有了
