### ISSUE TITLE
原神签到失效了

### ISSUE THREAD

**Issue by pooneyy** [y1ndan/genshinhelper2#38]
日志：
```
You have 1 「原神签到福利」 account configured.
Preparing to perform task for account 1...
Preparing to get user game roles information ...
Starting new HTTPS connection (1): api-takumi.mihoyo.com:443
https://api-takumi.mihoyo.com:443 "GET /binding/api/getUserGameRolesByCookie?game_biz=hk4e_cn HTTP/1.1" 405 None
TRACEBACK
Traceback (most recent call last):
  File "/var/user/genshincheckinhelper/main.py", line 245, in run_task
    raw_result = func(cookie)
  File "/var/user/genshincheckinhelper/main.py", line 90, in task2
    r = t.sign()
  File "/var/user/genshinhelper/core.py", line 115, in sign
    user_data = self.user_data
  File "/var/user/genshinhelper/core.py", line 101, in user_data
    sign_info = self.sign_info
  File "/var/user/genshinhelper/mihoyo.py", line 37, in sign_info
    roles_info = self.roles_info
  File "/var/user/genshinhelper/core.py", line 55, in roles_info
    response = request('get', url, headers=self.headers, cookies=self.cookie).json()
  File "/var/user/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/var/lang/python3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/var/lang/python3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/lang/python3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
RESULT:
🏆 原神签到福利
☁️ ✔ 0 · ✖ 1
🌈 No.1:
    Expecting value: line 1 column 1 (char 0)
```

**Comment by pooneyy** [comment]
更新到2.1.1即可
