### ISSUE TITLE
8.8 起获取不到实时便笺信息了

### ISSUE THREAD

**Issue by goreliu** [y1ndan/genshinhelper2#41]
版本：2.1.1

cookie_token 正确的情况：

```
{'data': None, 'message': 'Please login', 'retcode': 10001}
Traceback (most recent call last):
  File "/home/goreliu/git/site/www/genshin/genshin.py", line 32, in <module>
    for e in daily_note['expeditions']:
KeyError: 'expeditions'
```

cookie_token 错误的情况：

```
2022-08-08 10:49:34 ERROR 登录失效，请重新登录
Traceback (most recent call last):
  File "/home/goreliu/git/site/www/genshin/genshin.py", line 23, in <module>
    for i in ys.roles_info:
  File "/usr/lib/python3.10/site-packages/genshinhelper/core.py", line 58, in roles_info
    raise GenshinHelperException(response.get('message'))
genshinhelper.exceptions.GenshinHelperException: 登录失效，请重新登录
```

今天凌晨一点多还是正常的。重新登录也无效（cookie_token 不会改变），不知道是接口改了还是什么原因。用同样的 cookie_token，每日签到是正常的。

**Comment by y1ndan** [comment]
根据群友测试是可以用的。应该是你的cookie问题。

**Comment by goreliu** [comment]
> 根据群友测试是可以用的。应该是你的cookie问题。

今天白天也正常吗？我又重新获取了一次不一样的 cookie_token，还是同样的错误，已经登录成功了：

```
{'region': 'cn_gf01', 'game_uid': 'xxx', 'nickname': 'xxx', 'level': 59, 'region_name': '天空岛'}
```
具体内容还是：
```
{'data': None, 'message': 'Please login', 'retcode': 10001}
```
另外每日签到是正常的，应该说明 cookie_token 没问题，如果别人的正常，只能是我米游社账号有问题了，但我两个账号都是这样的。

**Comment by y1ndan** [comment]
你把cookie格式发下

**Comment by goreliu** [comment]
> 你把cookie格式发下

```
import genshinhelper as gh

cookies = 'account_id=277609xxx; cookie_token=koyx2JIF3TRbRm3kpDsXaiVGhn7Bu82Kxx2sXXXX'

for cookie in gh.utils.get_cookies(cookies):
    ys = gh.YuanShen(cookie)

    i = ys.roles_info[0]
    print(i)
    print(ys.get_daily_note(i['game_uid'], i['region']))
```

```
2022-08-08 13:52:50 INFO Preparing to get user game roles information ...
{'region': 'cn_gf01', 'game_uid': '175603xxx', 'nickname': 'xxx', 'level': 59, 'region_name': '天空岛'}
2022-08-08 13:52:51 INFO Preparing to get Yuan Shen daily note ...
{'role_id': '175603xxx', 'server': 'cn_gf01'}
{'data': None, 'message': 'Please login', 'retcode': 10001}
```

**Comment by y1ndan** [comment]
建议直接用成品

**Comment by y1ndan** [comment]
建议直接用成品

**Comment by goreliu** [comment]
我知道是怎么回事了，挂个代理后正常了，原来的 ip 被特别对待了。
