### ISSUE TITLE
total_sign_day问题

### ISSUE THREAD

**Issue by dawn-cmd** [y1ndan/genshinhelper2#57]
FunctionCompute python3 runtime inited.
FC Invoke Start RequestId: 3e30b06a-2aea-4b2c-9b2d-9b369c16330f
2022-08-26 00:42:10 3e30b06a-2aea-4b2c-9b2d-9b369c16330f [INFO] 
+----------------------------------------------------------------+
|               𒆙  Genshin Check-In Helper v1.0.3                |
+----------------------------------------------------------------+
Project      : genshinhelper
Description  : More than check-in for Genshin Impact.
PKG_Version  : 2.1.2
Author       : 银弹GCell(y1ndan)
Blog         : https://www.yindan.me
Channel      : https://t.me/genshinhelperupdates
------------------------------------------------------------------
2022-08-26 00:42:10 3e30b06a-2aea-4b2c-9b2d-9b369c16330f [INFO] Sleep for 264 seconds...
2022-08-26 00:46:34 3e30b06a-2aea-4b2c-9b2d-9b369c16330f [INFO] Starting...
2022-08-26 00:46:34 3e30b06a-2aea-4b2c-9b2d-9b369c16330f [INFO] You have 1 「原神签到福利」 account configured.
2022-08-26 00:46:34 3e30b06a-2aea-4b2c-9b2d-9b369c16330f [INFO] Preparing to perform task for account 1...
2022-08-26 00:46:34 3e30b06a-2aea-4b2c-9b2d-9b369c16330f [INFO] Preparing to get user game roles information ...
2022-08-26 00:46:34 3e30b06a-2aea-4b2c-9b2d-9b369c16330f [INFO] Preparing to get check-in information ...
2022-08-26 00:46:34 3e30b06a-2aea-4b2c-9b2d-9b369c16330f [ERROR] TRACEBACK
Traceback (most recent call last):
  File "/code/genshincheckinhelper/main.py", line 245, in run_task
    raw_result = func(cookie)
  File "/code/genshincheckinhelper/main.py", line 90, in task2
    r = t.sign()
  File "/code/genshinhelper/core.py", line 115, in sign
    user_data = self.user_data
  File "/code/genshinhelper/core.py", line 103, in user_data
    current_reward = self.current_reward
  File "/code/genshinhelper/core.py", line 86, in current_reward
    for i in sign_info
  File "/code/genshinhelper/core.py", line 86, in <listcomp>
    for i in sign_info
KeyError: 'total_sign_day'2022-08-26T04:46:34.288Z 3e30b06a-2aea-4b2c-9b2d-9b369c16330f [INFO] RESULT:
🏆 原神签到福利
☁️ ✔ 0 · ✖ 1
🌈 No.1:
    'total_sign_day'

2022-08-26 00:46:34 3e30b06a-2aea-4b2c-9b2d-9b369c16330f [INFO] Preparing to send notification ...
2022-08-26 00:46:34 3e30b06a-2aea-4b2c-9b2d-9b369c16330f [INFO] End of process run
FC Invoke End RequestId: 3e30b06a-2aea-4b2c-9b2d-9b369c16330f

**Comment by cpe1022** [comment]
+1 我也报这个错了

**Comment by hexsix** [comment]
+1
but same as https://github.com/y1ndan/genshinhelper2/issues/14

**Comment by cpe1022** [comment]
> +1 but same as #14

我解决了 cookie的问题，检查下获取的cookie 不要有什么 zh cn什么的东西 要有cookie_token，account_id就行了 我的是_ga_开头如果开头不是这个的话把前面的删除试试
