### ISSUE TITLE
米游社任务全失败了

### ISSUE THREAD

**Issue by piaoying9** [y1ndan/genshinhelper2#65]
运行环境:
ubuntu20.04  docker

运行日志:
2022-09-16 06:02:25 ERROR TRACEBACK
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/./genshincheckinhelper/main.py", line 245, in run_task
    raw_result = func(cookie)
  File "/app/./genshincheckinhelper/main.py", line 104, in task4
    r = t.run(26)
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/mihoyo.py", line 298, in run
    posts = self.get_posts(forum_id)
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/mihoyo.py", line 252, in get_posts
    response = request('get', url).json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-09-16 06:02:25 INFO Preparing to perform task for account 2...
2022-09-16 06:02:25 INFO Preparing to get user missions state ...
2022-09-16 06:02:26 INFO Preparing to check-in for 崩坏3 ...
2022-09-16 06:02:26 INFO Preparing to check-in for 原神 ...
2022-09-16 06:02:26 INFO Preparing to check-in for 崩坏2 ...
2022-09-16 06:02:27 INFO Preparing to check-in for 未定 事件簿 ...
2022-09-16 06:02:27 INFO Preparing to check-in for 大别 野 ...
2022-09-16 06:02:27 INFO Preparing to check-in for 崩坏: 星穹铁道 ...
2022-09-16 06:02:28 INFO Preparing to check-in for 绝区 零 ...
2022-09-16 06:02:28 INFO Preparing to get posts of 原神 ...
2022-09-16 06:02:28 ERROR TRACEBACK
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/./genshincheckinhelper/main.py", line 245, in run_task
    raw_result = func(cookie)
  File "/app/./genshincheckinhelper/main.py", line 104, in task4
    r = t.run(26)
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/mihoyo.py", line 298, in run
    posts = self.get_posts(forum_id)
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/mihoyo.py", line 252, in get_posts
    response = request('get', url).json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-09-16 06:02:28 INFO Preparing to perform task for account 3...
2022-09-16 06:02:28 INFO Preparing to get user missions state ...
2022-09-16 06:02:29 INFO Preparing to check-in for 崩坏3 ...
2022-09-16 06:02:29 INFO Preparing to check-in for 原神 ...
2022-09-16 06:02:30 INFO Preparing to check-in for 崩坏2 ...
2022-09-16 06:02:30 INFO Preparing to check-in for 未定 事件簿 ...
2022-09-16 06:02:30 INFO Preparing to check-in for 大别 野 ...
2022-09-16 06:02:31 INFO Preparing to check-in for 崩坏: 星穹铁道 ...
2022-09-16 06:02:31 INFO Preparing to check-in for 绝区 零 ...
2022-09-16 06:02:31 INFO Preparing to get posts of 原神 ...
2022-09-16 06:02:32 ERROR TRACEBACK
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/./genshincheckinhelper/main.py", line 245, in run_task
    raw_result = func(cookie)
  File "/app/./genshincheckinhelper/main.py", line 104, in task4
    r = t.run(26)
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/mihoyo.py", line 298, in run
    posts = self.get_posts(forum_id)
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/mihoyo.py", line 252, in get_posts
    response = request('get', url).json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-09-16 06:02:32 INFO Preparing to perform task for account 4...
2022-09-16 06:02:32 INFO Preparing to get user missions state ...
2022-09-16 06:02:32 INFO Preparing to check-in for 崩坏3 ...
2022-09-16 06:02:32 INFO Preparing to check-in for 原神 ...
2022-09-16 06:02:33 INFO Preparing to check-in for 崩坏2 ...
2022-09-16 06:02:33 INFO Preparing to check-in for 未定 事件簿 ...
2022-09-16 06:02:33 INFO Preparing to check-in for 大别 野 ...
2022-09-16 06:02:34 INFO Preparing to check-in for 崩坏: 星穹铁道 ...
2022-09-16 06:02:34 INFO Preparing to check-in for 绝区 零 ...
2022-09-16 06:02:35 INFO Preparing to get posts of 原神 ...
2022-09-16 06:02:35 ERROR TRACEBACK
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/./genshincheckinhelper/main.py", line 245, in run_task
    raw_result = func(cookie)
  File "/app/./genshincheckinhelper/main.py", line 104, in task4
    r = t.run(26)
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/mihoyo.py", line 298, in run
    posts = self.get_posts(forum_id)
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/mihoyo.py", line 252, in get_posts
    response = request('get', url).json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

推送截图:
![Screenshot_2022-09-16-08-57-28-228-edit_com tencent mm](https://user-images.githubusercontent.com/45061886/190533958-c13fcd59-58a6-455d-9b14-b2cc7adede82.jpg)

**Comment by piaoying9** [comment]
更新已解决，感谢！
