### ISSUE TITLE
大佬, 这个报错是我cookie格式有问题吗？

### ISSUE THREAD

**Issue by grinxxoo** [y1ndan/genshinhelper2#72]

**Comment by grinxxoo** [comment]
Traceback (most recent call last):
  File "/app/./genshincheckinhelper/main.py", line 245, in run_task
    raw_result = func(cookie)
  File "/app/./genshincheckinhelper/main.py", line 90, in task2
    r = t.sign()
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/core.py", line 115, in sign
    user_data = self.user_data
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/core.py", line 101, in user_data
    sign_info = self.sign_info
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/mihoyo.py", line 37, in sign_info
    roles_info = self.roles_info
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/core.py", line 55, in roles_info
    response = request('get', url, headers=self.headers, cookies=self.cookie).json()
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/utils.py", line 227, in request
    raise e
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/utils.py", line 223, in request
    response = s.request(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 471, in prepare_request
    cookies = cookiejar_from_dict(cookies)
  File "/usr/local/lib/python3.10/site-packages/requests/cookies.py", line 537, in cookiejar_from_dict
    cookiejar.set_cookie(create_cookie(name, cookie_dict[name]))

**Comment by grinxxoo** [comment]
现在获取到的cookie都是以下格式：
cookie_token_v2=v2_xxxxxxxx; account_id_v2=xxxxxxxx;

**Comment by Night-stars-1** [comment]
> 现在获取到的cookie都是以下格式： cookie_token_v2=v2_xxxxxxxx; account_id_v2=xxxxxxxx;

现在cookie确实是这样的，但最后一个;要去掉，也可能是你cookie抓错了

**Comment by grinxxoo** [comment]
> > 现在获取到的cookie都是以下格式： cookie_token_v2=v2_xxxxxxxx; account_id_v2=xxxxxxxx;
> 
> 现在cookie确实是这样的，但最后一个;要去掉，也可能是你cookie抓错了

cookie没错后面的冒号也没加，不知道啥原因，cookie用在隔壁的项目是可用的，估计是我拉的库没有正确配置 后面的云ys和微博都是ok的
