### ISSUE TITLE
不知道cookie token有个v2正常吗，另外连接有问题，运行报错Login expired.Please log in again

### ISSUE THREAD

**Issue by LeSnran** [y1ndan/genshinhelper2#77]

**Comment by xiaokang00010** [comment]
YuanShen对应的是国服 Genshin对应的是外服 理论上来说在国服签到失败应该是"登录失效，请重新登录" 你看看代码？

**Comment by yq60523** [comment]
同，我也出现了这个问题

**Comment by yihuanlin** [comment]
对我用的tokenv2不行，logs如下：
```
2023-11-24 00:45:32 INFO You have 1 「HoYoLAB Community」 account configured.
2023-11-24 00:45:32 INFO Preparing to perform task for account 1...
2023-11-24 00:45:32 INFO Preparing to get check-in information ...
2023-11-24 00:45:55 INFO Preparing to get user game roles information ...
2023-11-24 00:45:58 ERROR TRACEBACK
Traceback (most recent call last):
  File "/app/./genshincheckinhelper/main.py", line 245, in run_task
    raw_result = func(cookie)
  File "/app/./genshincheckinhelper/main.py", line 83, in task1
    r = t.sign()
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/core.py", line 115, in sign
    user_data = self.user_data
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/core.py", line 103, in user_data
    current_reward = self.current_reward
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/core.py", line 84, in current_reward
    return [
  File "/usr/local/lib/python3.10/site-packages/genshinhelper/core.py", line 85, in <listcomp>
    self.get_current_reward(i['total_sign_day'], i['is_sign'])
```
结果是
```
🏆 HoYoLAB Community
☁️ ✔ 0 · ✖ 1
🌈 No.1:
    'total_sign_day'
```
另外Discord Webhook好像也没自动通知
