### ISSUE TITLE
获取探险信息失败报错

### ISSUE THREAD

**Issue by JarvisPongSky** [y1ndan/genshinhelper2#9]
![a2eb238bd3ce8e3ae1a58d6bfdcea6d](https://user-images.githubusercontent.com/53456132/147680485-351a57da-6358-4b11-8cd7-d09e32444cef.png)

日志信息如下：

```log
2021-12-29 15:43:14 INFO Preparing to get Yuan Shen daily note ...
2021-12-29 15:43:14 INFO 实时便笺
    �浑水摸鱼真君 58 天空岛
    原粹树脂: 45 / 160 将于2021-12-30 06:57:36全部恢复
    今日委托: 4 / 4
    周本减半: 0 / 3
    探索派遣: 5 / 5
      └─ Ambor      剩余时间   8小时40分钟
      └─ Fischl     剩余时间   3小时39分钟
      └─ Chongyun   剩余时间   3小时39分钟
      └─ Bennett    剩余时间   3小时39分钟
      └─ Sara       剩余时间   3小时39分钟

2021-12-29 15:43:14 INFO 原神签到小助手提醒您: 未满足推送条件, 监控模式运行中...
2021-12-29 15:43:14 INFO Preparing to get user game roles information ...
2021-12-29 15:43:15 INFO Preparing to get Yuan Shen daily note ...
Traceback (most recent call last):
  File "/app/./genshincheckinhelper/main.py", line 399, in <module>
    main()
  File "/app/./genshincheckinhelper/main.py", line 388, in main
    run_once()
  File "/app/./genshincheckinhelper/main.py", line 384, in run_once
    job2()
  File "/app/./genshincheckinhelper/main.py", line 309, in job2
    for e in daily_note['expeditions']:
KeyError: 'expeditions'

```

**Comment by y1ndan** [comment]
米游社实时便笺权限没开

**Comment by JarvisPongSky** [comment]
![2be5f7439e6377715f4cef6c4ba7ba4](https://user-images.githubusercontent.com/53456132/147681762-19f16903-4f66-458d-a252-b06ebb66c7d7.jpg)

权限有开，我初步排查看 log 五次派遣都有打印，估计是循环大于5，后续进去报错了

**Comment by JarvisPongSky** [comment]
我打印了 `log.info(daily_note)` 信息 如下

```json
{
    "current_resin": 49,
    "max_resin": 160,
    "resin_recovery_time": "52879",
    "finished_task_num": 4,
    "total_task_num": 4,
    "is_extra_task_reward_received": true,
    "remain_resin_discount_num": 0,
    "resin_discount_num_limit": 3,
    "current_expedition_num": 5,
    "max_expedition_num": 5,
    "expeditions": [
        {
            "avatar_side_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Ambor.png",
            "status": "Ongoing",
            "remained_time": "29233"
        },
        {
            "avatar_side_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Fischl.png",
            "status": "Ongoing",
            "remained_time": "11185"
        },
        {
            "avatar_side_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Chongyun.png",
            "status": "Ongoing",
            "remained_time": "11185"
        },
        {
            "avatar_side_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Bennett.png",
            "status": "Ongoing",
            "remained_time": "11185"
        },
        {
            "avatar_side_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Sara.png",
            "status": "Ongoing",
            "remained_time": "11185"
        }
    ]
}
```

**Comment by JarvisPongSky** [comment]
> 米游社实时便笺权限没开

欸，我问问我朋友是不是没开，可能是这个问题导致的。

**Comment by y1ndan** [comment]
你的检测没有间隔的？

**Comment by JarvisPongSky** [comment]
> 你的检测没有间隔的？

config.json `RANDOM_SLEEP_SECS_RANGE`  延迟参数目前被我设置成  `0-0` 了。

**Comment by JarvisPongSky** [comment]
> 

我的 config.json 除了  `RANDOM_SLEEP_SECS_RANGE` 参数被我改成 `0-0` 以外，其他延迟参数都没变。

```json
{
  "LANGUAGE": "zh",
  "RANDOM_SLEEP_SECS_RANGE": "0-300",
  "CHECK_IN_TIME": "00:05",
  "CHECK_RESIN_SECS": 900,
  "RESIN_THRESHOLD": 150,
  "RESIN_TIMER_DO_NOT_DISTURB": "23:00-07:00"
}
```

**Comment by y1ndan** [comment]
如果配置了两个账号的话，另一个账号应该没有开权限。

**Comment by JarvisPongSky** [comment]
> 如果配置了两个账号的话，另一个账号应该没有开权限。

这个应该得增加容错机制，如果没开权限直接报错，在容器编排服务中部署（swarm、k8s）会导致容器一直重新调度启动。

刚好第一次启动容器会自动签到，并且通知，会一直无限循环重启签到通知....
